server:
  image: xuxuebin/ngrok
  ports:
    - "44063:80"
    - "32782:443"
    - "32783:4443"
  volumes:
    - ./data/ngrok:/myfiles
  environment:
    - DOMAIN=tunnel.smartcellphone.cn
  command: /bin/sh /server.sh
